// src/lib/counties.ts
// All 47 Kenyan counties with towns, slugs, and region metadata

export interface CountyData {
  name: string;
  slug: string;
  region: string;
  majorTowns: string[];
  responseTime: string;
  description: string;
}

export const COUNTIES: CountyData[] = [
  {
    name: 'Nairobi',
    slug: 'nairobi',
    region: 'Nairobi',
    majorTowns: ['CBD', 'Westlands', 'Karen', 'Kilimani', 'Lavington', 'Upperhill', 'Parklands', 'Gigiri', 'Runda', 'South B', 'South C', 'Hurlingham', 'Industrial Area'],
    responseTime: '1–2 business days',
    description: 'the capital and largest city of Kenya',
  },
  {
    name: 'Mombasa',
    slug: 'mombasa',
    region: 'Coast',
    majorTowns: ['Mombasa CBD', 'Nyali', 'Bamburi', 'Likoni', 'Changamwe', 'Kisauni', 'Mikindani'],
    responseTime: '2–3 business days',
    description: 'Kenya\'s second largest city and major port',
  },
  {
    name: 'Kisumu',
    slug: 'kisumu',
    region: 'Nyanza',
    majorTowns: ['Kisumu CBD', 'Kondele', 'Milimani', 'Mamboleo', 'Nyalenda', 'Kolwa'],
    responseTime: '2–3 business days',
    description: 'the third largest city in Kenya on Lake Victoria',
  },
  {
    name: 'Nakuru',
    slug: 'nakuru',
    region: 'Rift Valley',
    majorTowns: ['Nakuru CBD', 'Milimani', 'Kiamunyi', 'Naivasha', 'Gilgil', 'Molo', 'Njoro'],
    responseTime: '2–3 business days',
    description: 'a major commercial hub in the Rift Valley',
  },
  {
    name: 'Uasin Gishu',
    slug: 'uasin-gishu',
    region: 'Rift Valley',
    majorTowns: ['Eldoret', 'Turbo', 'Ziwa', 'Huruma', 'Langas', 'Pioneer'],
    responseTime: '3–4 business days',
    description: 'home to Eldoret, Kenya\'s fifth largest city',
  },
  {
    name: 'Kiambu',
    slug: 'kiambu',
    region: 'Central',
    majorTowns: ['Thika', 'Ruiru', 'Kiambu Town', 'Limuru', 'Githunguri', 'Kikuyu', 'Karuri'],
    responseTime: '1–2 business days',
    description: 'a rapidly growing county neighbouring Nairobi',
  },
  {
    name: 'Machakos',
    slug: 'machakos',
    region: 'Eastern',
    majorTowns: ['Machakos Town', 'Athi River', 'Kangundo', 'Tala', 'Mwala', 'Matungulu'],
    responseTime: '2–3 business days',
    description: 'a thriving business county near Nairobi',
  },
  {
    name: 'Kajiado',
    slug: 'kajiado',
    region: 'Rift Valley',
    majorTowns: ['Kajiado Town', 'Ngong', 'Kitengela', 'Ongata Rongai', 'Kiserian', 'Namanga'],
    responseTime: '2–3 business days',
    description: 'a fast-growing county bordering Nairobi',
  },
  {
    name: "Murang'a",
    slug: 'muranga',
    region: 'Central',
    majorTowns: ["Murang'a Town", 'Kangema', 'Maragua', 'Kenol', 'Kiriaini', 'Kahuro'],
    responseTime: '2–3 business days',
    description: 'an agricultural county in the Central region',
  },
  {
    name: 'Nyeri',
    slug: 'nyeri',
    region: 'Central',
    majorTowns: ['Nyeri Town', 'Othaya', 'Karatina', 'Mukurweini', 'Tetu', 'Kieni'],
    responseTime: '2–3 business days',
    description: 'a key Central Kenya business and tourism hub',
  },
  {
    name: 'Meru',
    slug: 'meru',
    region: 'Eastern',
    majorTowns: ['Meru Town', 'Nkubu', 'Timau', 'Maua', 'Chuka', 'Mikinduri'],
    responseTime: '3–4 business days',
    description: 'a growing commercial hub in Eastern Kenya',
  },
  {
    name: 'Embu',
    slug: 'embu',
    region: 'Eastern',
    majorTowns: ['Embu Town', 'Runyenjes', 'Siakago', 'Ishiara', 'Mbeere'],
    responseTime: '2–3 business days',
    description: 'a strategic county at the foot of Mount Kenya',
  },
  {
    name: 'Kirinyaga',
    slug: 'kirinyaga',
    region: 'Central',
    majorTowns: ['Kerugoya', 'Kutus', 'Wanguru', 'Sagana', 'Kagio'],
    responseTime: '2–3 business days',
    description: 'a productive county in the shadow of Mount Kenya',
  },
  {
    name: 'Laikipia',
    slug: 'laikipia',
    region: 'Rift Valley',
    majorTowns: ['Nanyuki', 'Rumuruti', 'Doldol', 'Nyahururu', 'Kinamba'],
    responseTime: '3–4 business days',
    description: 'a scenic county known for tourism and ranching',
  },
  {
    name: 'Nyandarua',
    slug: 'nyandarua',
    region: 'Central',
    majorTowns: ['Ol Kalou', 'Engineer', 'Njabini', 'Nyahururu', 'Ndaragwa'],
    responseTime: '3–4 business days',
    description: 'a highland county in Central Kenya',
  },
  {
    name: 'Tharaka-Nithi',
    slug: 'tharaka-nithi',
    region: 'Eastern',
    majorTowns: ['Chuka', 'Marimanti', 'Kathwana', 'Gatunga'],
    responseTime: '3–5 business days',
    description: 'a county in Eastern Kenya with rich agricultural land',
  },
  {
    name: 'Kitui',
    slug: 'kitui',
    region: 'Eastern',
    majorTowns: ['Kitui Town', 'Mwingi', 'Mutomo', 'Migwani', 'Zombe'],
    responseTime: '3–5 business days',
    description: 'a large Eastern Kenya county with diverse industries',
  },
  {
    name: 'Makueni',
    slug: 'makueni',
    region: 'Eastern',
    majorTowns: ['Wote', 'Emali', 'Kibwezi', 'Mtito Andei', 'Sultan Hamud'],
    responseTime: '3–4 business days',
    description: 'a strategic county along the Nairobi–Mombasa corridor',
  },
  {
    name: 'Garissa',
    slug: 'garissa',
    region: 'North Eastern',
    majorTowns: ['Garissa Town', 'Dadaab', 'Ijara', 'Fafi'],
    responseTime: '5–7 business days',
    description: 'the capital of North Eastern Kenya',
  },
  {
    name: 'Wajir',
    slug: 'wajir',
    region: 'North Eastern',
    majorTowns: ['Wajir Town', 'Habaswein', 'Bute', 'Griftu'],
    responseTime: '5–7 business days',
    description: 'a North Eastern Kenya county near Ethiopia',
  },
  {
    name: 'Mandera',
    slug: 'mandera',
    region: 'North Eastern',
    majorTowns: ['Mandera Town', 'Elwak', 'Takaba', 'Banisa'],
    responseTime: '5–7 business days',
    description: 'Kenya\'s northernmost county bordering Ethiopia and Somalia',
  },
  {
    name: 'Marsabit',
    slug: 'marsabit',
    region: 'Eastern',
    majorTowns: ['Marsabit Town', 'Moyale', 'Laisamis', 'Loiyangalani'],
    responseTime: '5–7 business days',
    description: 'Kenya\'s largest county by area in Northern Kenya',
  },
  {
    name: 'Isiolo',
    slug: 'isiolo',
    region: 'Eastern',
    majorTowns: ['Isiolo Town', 'Merti', 'Garbatulla'],
    responseTime: '4–6 business days',
    description: 'a gateway county to Northern Kenya',
  },
  {
    name: 'Samburu',
    slug: 'samburu',
    region: 'Rift Valley',
    majorTowns: ['Maralal', 'Baragoi', 'Wamba'],
    responseTime: '4–6 business days',
    description: 'a scenic Rift Valley county known for Samburu National Reserve',
  },
  {
    name: 'Turkana',
    slug: 'turkana',
    region: 'Rift Valley',
    majorTowns: ['Lodwar', 'Kakuma', 'Lokichar', 'Kalokol'],
    responseTime: '5–7 business days',
    description: 'Kenya\'s second largest county in Northwestern Kenya',
  },
  {
    name: 'West Pokot',
    slug: 'west-pokot',
    region: 'Rift Valley',
    majorTowns: ['Kapenguria', 'Kitale (border)', 'Alale', 'Chepareria'],
    responseTime: '4–6 business days',
    description: 'a Northwestern Rift Valley county',
  },
  {
    name: 'Elgeyo-Marakwet',
    slug: 'elgeyo-marakwet',
    region: 'Rift Valley',
    majorTowns: ['Iten', 'Eldoret (border)', 'Kabarnet (border)', 'Tambach'],
    responseTime: '3–5 business days',
    description: 'a Rift Valley county known for athletics',
  },
  {
    name: 'Nandi',
    slug: 'nandi',
    region: 'Rift Valley',
    majorTowns: ['Kapsabet', 'Nandi Hills', 'Mosoriot', 'Lessos'],
    responseTime: '3–4 business days',
    description: 'a productive tea and athletics county in the Rift Valley',
  },
  {
    name: 'Baringo',
    slug: 'baringo',
    region: 'Rift Valley',
    majorTowns: ['Kabarnet', 'Eldama Ravine', 'Marigat', 'Mogotio'],
    responseTime: '3–5 business days',
    description: 'a Rift Valley county with scenic lakes and valleys',
  },
  {
    name: 'Kakamega',
    slug: 'kakamega',
    region: 'Western',
    majorTowns: ['Kakamega Town', 'Mumias', 'Butere', 'Lugari', 'Malava'],
    responseTime: '3–4 business days',
    description: 'the most populous county in Western Kenya',
  },
  {
    name: 'Vihiga',
    slug: 'vihiga',
    region: 'Western',
    majorTowns: ['Mbale', 'Vihiga Town', 'Hamisi', 'Emuhaya'],
    responseTime: '3–4 business days',
    description: 'Kenya\'s most densely populated county in Western Kenya',
  },
  {
    name: 'Bungoma',
    slug: 'bungoma',
    region: 'Western',
    majorTowns: ['Bungoma Town', 'Webuye', 'Kimilili', 'Chwele', 'Sirisia'],
    responseTime: '3–4 business days',
    description: 'a leading agricultural county in Western Kenya',
  },
  {
    name: 'Busia',
    slug: 'busia',
    region: 'Western',
    majorTowns: ['Busia Town', 'Malaba', 'Port Victoria', 'Funyula'],
    responseTime: '3–5 business days',
    description: 'a border county connecting Kenya and Uganda',
  },
  {
    name: 'Siaya',
    slug: 'siaya',
    region: 'Nyanza',
    majorTowns: ['Siaya Town', 'Bondo', 'Ugunja', 'Yala', 'Ndori'],
    responseTime: '3–4 business days',
    description: 'a Nyanza county on the shores of Lake Victoria',
  },
  {
    name: 'Homa Bay',
    slug: 'homa-bay',
    region: 'Nyanza',
    majorTowns: ['Homa Bay Town', 'Oyugis', 'Kendu Bay', 'Mbita', 'Ndhiwa'],
    responseTime: '3–5 business days',
    description: 'a Nyanza county on Lake Victoria known for tourism',
  },
  {
    name: 'Migori',
    slug: 'migori',
    region: 'Nyanza',
    majorTowns: ['Migori Town', 'Rongo', 'Uriri', 'Awendo', 'Isebania'],
    responseTime: '3–5 business days',
    description: 'a Nyanza county bordering Tanzania and Uganda',
  },
  {
    name: 'Kisii',
    slug: 'kisii',
    region: 'Nyanza',
    majorTowns: ['Kisii Town', 'Ogembo', 'Keroka', 'Suneka', 'Nyamache'],
    responseTime: '3–4 business days',
    description: 'a densely populated agricultural county in Nyanza',
  },
  {
    name: 'Nyamira',
    slug: 'nyamira',
    region: 'Nyanza',
    majorTowns: ['Nyamira Town', 'Keroka', 'Nyansiongo', 'Magombo'],
    responseTime: '3–5 business days',
    description: 'a tea-growing county in the Nyanza region',
  },
  {
    name: 'Bomet',
    slug: 'bomet',
    region: 'Rift Valley',
    majorTowns: ['Bomet Town', 'Sotik', 'Longisa', 'Chesoen'],
    responseTime: '3–4 business days',
    description: 'a tea county in the southwestern Rift Valley',
  },
  {
    name: 'Kericho',
    slug: 'kericho',
    region: 'Rift Valley',
    majorTowns: ['Kericho Town', 'Litein', 'Londiani', 'Kipkelion'],
    responseTime: '3–4 business days',
    description: 'Kenya\'s premier tea-growing county in the Rift Valley',
  },
  {
    name: 'Narok',
    slug: 'narok',
    region: 'Rift Valley',
    majorTowns: ['Narok Town', 'Kilgoris', 'Emurua Dikirr', 'Ololulung\'a'],
    responseTime: '3–4 business days',
    description: 'home to the Maasai Mara National Reserve',
  },
  {
    name: 'Trans Nzoia',
    slug: 'trans-nzoia',
    region: 'Rift Valley',
    majorTowns: ['Kitale', 'Endebess', 'Saboti', 'Cherangany'],
    responseTime: '3–5 business days',
    description: 'Kenya\'s breadbasket county in the Rift Valley',
  },
  {
    name: 'Taita-Taveta',
    slug: 'taita-taveta',
    region: 'Coast',
    majorTowns: ['Voi', 'Taveta', 'Wundanyi', 'Mwatate'],
    responseTime: '3–5 business days',
    description: 'a scenic Coast county at the foot of the Taita Hills',
  },
  {
    name: 'Kwale',
    slug: 'kwale',
    region: 'Coast',
    majorTowns: ['Kwale Town', 'Msambweni', 'Ukunda', 'Diani', 'Shimba Hills'],
    responseTime: '3–4 business days',
    description: 'a coastal county known for beaches and mineral resources',
  },
  {
    name: 'Kilifi',
    slug: 'kilifi',
    region: 'Coast',
    majorTowns: ['Kilifi Town', 'Malindi', 'Watamu', 'Mtwapa', 'Mariakani'],
    responseTime: '3–4 business days',
    description: 'a coastal county with world-class beaches and resorts',
  },
  {
    name: 'Lamu',
    slug: 'lamu',
    region: 'Coast',
    majorTowns: ['Lamu Town', 'Witu', 'Hindi', 'Mokowe', 'Mpeketoni'],
    responseTime: '4–6 business days',
    description: 'a historic island county on the Kenya Coast',
  },
  {
    name: 'Tana River',
    slug: 'tana-river',
    region: 'Coast',
    majorTowns: ['Hola', 'Garsen', 'Bura', 'Madogo'],
    responseTime: '4–6 business days',
    description: 'a large coastal county along the Tana River',
  },
];

export const getCountyBySlug = (slug: string): CountyData | undefined =>
  COUNTIES.find(c => c.slug === slug);

export const ALL_COUNTY_SLUGS = COUNTIES.map(c => c.slug);
